"""One-time generator script (NOT part of the tutorial runtime).

Uses PySCF + OpenFermion to compute exact, literature-reproducible qubit
Hamiltonians for H2 and LiH in STO-3G, Jordan-Wigner mapped. The printed
output is hand-verified (ground-state energy checked against known values)
and then copied into common/hamiltonians.py as hardcoded coefficients, so
that the tutorial itself has no PySCF/OpenFermion dependency.

Run once with:  python3 tools/generate_hamiltonians.py
"""
import numpy as np
from openfermion.chem import MolecularData
from openfermionpyscf import run_pyscf
from openfermion.transforms import get_fermion_operator, jordan_wigner
from openfermion.linalg import get_sparse_operator
import scipy.sparse.linalg as spla


def build(geometry, basis, multiplicity, charge, name, active_space=None):
    mol = MolecularData(geometry, basis, multiplicity, charge, description=name)
    mol = run_pyscf(mol, run_scf=True, run_fci=True)
    print(f"\n=== {name} ===")
    print(f"HF energy:  {mol.hf_energy:.10f} Ha")
    print(f"FCI energy: {mol.fci_energy:.10f} Ha")

    if active_space is None:
        fermion_H = mol.get_molecular_hamiltonian()
    else:
        occ_indices, active_indices = active_space
        fermion_H = mol.get_molecular_hamiltonian(
            occupied_indices=occ_indices, active_indices=active_indices
        )

    fermion_op = get_fermion_operator(fermion_H)
    qubit_op = jordan_wigner(fermion_op)
    qubit_op.compress(abs_tol=1e-10)

    n_qubits = 2 * (len(active_space[1]) if active_space else mol.n_orbitals)
    sparse_H = get_sparse_operator(qubit_op, n_qubits=n_qubits)
    eigval, _ = spla.eigsh(sparse_H, k=1, which="SA")
    print(f"n_qubits: {n_qubits}")
    print(f"Ground state energy from JW qubit H (sparse diag): {eigval[0]:.10f} Ha")

    terms = []
    for pauli_tuple, coeff in qubit_op.terms.items():
        c = coeff.real
        if abs(c) < 1e-10:
            continue
        if len(pauli_tuple) == 0:
            label = "I"
        else:
            label = " ".join(f"{op}{idx}" for idx, op in pauli_tuple)
        terms.append((label, c))

    terms.sort(key=lambda t: (t[0] != "I", t[0]))
    print(f"n_terms: {len(terms)}")
    for label, c in terms:
        print(f"  {c: .12f}   {label}")

    return terms, n_qubits, mol.fci_energy


def emit_python(varname, terms, n_qubits, out):
    """Emit a ready-to-paste Python list literal of (coeff, 'PauliString') terms."""
    out.write(f"{varname}_N_QUBITS = {n_qubits}\n")
    out.write(f"{varname}_TERMS = [\n")
    for label, c in terms:
        pauli_str = "I" * n_qubits if label == "I" else None
        if pauli_str is None:
            ops = ["I"] * n_qubits
            for tok in label.split():
                op, idx = tok[0], int(tok[1:])
                ops[idx] = op
            pauli_str = "".join(ops)
        out.write(f"    ({float(c)!r}, {pauli_str!r}),\n")
    out.write("]\n\n")


if __name__ == "__main__":
    # H2, STO-3G, equilibrium bond length 0.7414 Angstrom, full 4-qubit JW map
    h2_terms, h2_nq, h2_fci = build(
        geometry=[("H", (0, 0, 0)), ("H", (0, 0, 0.7414))],
        basis="sto-3g",
        multiplicity=1,
        charge=0,
        name="H2_sto3g_0.7414A",
    )

    # LiH, STO-3G, equilibrium bond length 1.5949 Angstrom, reduced active
    # space: freeze the Li 1s core orbital, active = 4 spatial orbitals
    # (Li 2s/2p_z-like + H 1s bonding/antibonding) -> 8 qubits, a standard
    # reduction used throughout the VQE literature to keep LiH tractable.
    lih_terms, lih_nq, lih_fci = build(
        geometry=[("Li", (0, 0, 0)), ("H", (0, 0, 1.5949))],
        basis="sto-3g",
        multiplicity=1,
        charge=0,
        name="LiH_sto3g_1.5949A_reduced",
        active_space=([0], [1, 2, 3, 4]),
    )

    with open("tools/_generated_hamiltonians.py", "w") as f:
        f.write('"""Auto-generated by tools/generate_hamiltonians.py. Do not hand-edit.\n\n')
        f.write(f"H2 FCI energy:  {h2_fci:.10f} Ha (sto-3g, R=0.7414 A, 4 qubits, JW)\n")
        f.write(f"LiH FCI energy: {lih_fci:.10f} Ha (sto-3g, R=1.5949 A, active-space, 8 qubits, JW)\n")
        f.write('"""\n\n')
        emit_python("H2", h2_terms, h2_nq, f)
        emit_python("LIH", lih_terms, lih_nq, f)

    print("\n\nWrote tools/_generated_hamiltonians.py")
    print("Copy the H2_TERMS / LIH_TERMS lists into common/hamiltonians.py")
